from docx import Document
from docx.shared import Inches
import pyttsx3


def speak(text):
    pyttsx3.speak(text)


document = Document()

# profile picture
profile_pic = input(
    'Enter profile pic name with extension (example me.png), make sure file exists in the current folder ')
document.add_picture(profile_pic, width=Inches(1.5))

# name, phone number and email details
first_name = input('What is your first name? ')
last_name = input('What is your last name? ')
speak('Hello' + first_name + ' ' + last_name + ' how are you today?')

speak('What is your phone number?')
phone_number = input('What is your phone number? ')

speak('What is your email?')
email = input('What is your email? ')

document.add_paragraph(
    first_name + ' ' + last_name + ' | ' + phone_number + ' | ' + email).bold = True

# about me
document.add_heading('About me')
speak('Tell us bit about yourself?')
document.add_paragraph(
    input('Tell about yourself? ')
)


# work experience
more_experience = True

speak('Lets add experience now')


def add_experience():
    p = document.add_paragraph()
    company = input('Enter Company ')
    from_date = input('From Date (DD/MM/YYYY) ')
    to_date = input('To date (DD/MM/YYYY) or Present ')

    p.add_run(company + ' ').bold = True
    p.add_run(from_date + '-' + to_date + '\n').italic = True

    experience_details = input(
        'Describe your roles & responsibilities at ' + company + ' '
    )

    p.add_run(experience_details)


document.add_heading('Work Experience')
add_experience()
while more_experience == True:
    more = input('Add one more experience (Y/N)? ')

    if more == 'Y':
        add_experience()
    else:
        more_experience = False


# skills
speak('Lets add skills now')


def add_skills():
    p = document.add_paragraph()
    skill = input('Enter skill ')
    years = input('How many years of experience? ')

    p.add_run(skill + ': ').bold = True
    p.add_run(years + ' year(s)').italic = True
    p.style = 'List Bullet'


document.add_heading('Skills')
add_skills()
while True:
    more = input('Add one more skill (Y/N)? ')

    if more == 'Y':
        add_skills()
    else:
        break

# footer
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = 'CV is generated by Haresh'

document.save('cv.docx')
